### ISSUE TITLE
Just Notes

### ISSUE THREAD

**Issue by athiasjerome** [videlanicolas/assimilator#1]
Hi,

Just discovering the project, sounds promising. (and interesting for https://github.com/OpenC2-org )

In case it helps: https://github.com/google/capirca

Cheers

**Comment by videlanicolas** [comment]
Sounds cools! I aim to make an API wrapper over all possible firewall technologies, so as one can have an easier way to configure Firewalls. That repo could have been useful to me on previous months when I fought with Junos and Panos cli and api.

I'll be showing assimilator on BlackHat 2017: https://www.blackhat.com/us-17/arsenal.html#assimilator
